title: "БЛОГ.ПЛАЗМА72"
author: "ПЛАЗМА72"
description: "Полезные статьи о лазерной и плазменной резке металла: режимы резки, настройки станков, проекты и новости от ПЛАЗМА72."
url: "https://plasma72tob.github.io"
baseurl: ""

# SEO Settings
lang: ru
timezone: Europe/Moscow # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "tobolsk77@yandex.ru"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
pinterest_username: plasma72
youtube_username: "@PLASMA_72"
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"


# Локализация
minima:
  social_links:
    - { platform: youtube, user_url: "https://www.youtube.com/@plasma_72" }
    - { platform: pinterest, user_url: "https://pinterest.com/plasma72" }

# Переводы для темы
translations:
  posts: "Статьи"

rss: rss

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap settings
sitemap:
  priority: 0.8
  changefreq: 'weekly'

# SEO Plugin settings
twitter:
  username: plasma72
  
social:
  name: ПЛАЗМА72
  links:
    - https://www.youtube.com/channel/PLASMA_72
    - https://pinterest.com/plasma72

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
