title: "БЛОГ - Лазерная и плазменная резка мателла"
author: "ПЛАЗМА72"
description: "Свяжитесь с нами для покупки станка с доставкой в любой город РФ и РБ. " # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "tobolsk77@yandex.ru"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
pinterest_username: plasma72
youtube_username: PLASMA_72
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

# Локализация
minima:
  social_links:
    - { platform: youtube, user_url: "https://www.youtube.com/channel/@PLASMA_72" }
    - { platform: pinterest, user_url: "https://pinterest.com/plasma72" }

# Переводы для темы
translations:
  posts: "Статьи"

rss: rss

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
